query {
  Invoice_aggregate(
    filter_input: {
      where: { BillingCountry: { _eq: "USA" } }
      order_by: { InvoiceId: Asc }
      offset: 5
      limit: 10
    }
  ) {
    BillingState {
      _min
      _max
      _count_distinct
    }
    InvoiceId {
      min: _min
      max: _max
      count: _count
    }
    Total {
      _min
      _max
      _sum
      _stddev
    }
    count_all: _count
  }
}
