DROP VIEW hdb_catalog.hdb_scheduled_events_stats;
DROP TABLE hdb_catalog.hdb_scheduled_event_invocation_logs;
DROP TABLE hdb_catalog.hdb_scheduled_events;
DROP TABLE hdb_catalog.hdb_scheduled_trigger;
