type: bulk
args:

- type: mssql_run_sql
  args:
    source: mssql
    sql: |
      -- insert data
      INSERT INTO author (name)
        VALUES
        ('Author 1'),
        ('Author 2')
      ;
      INSERT INTO article (title,content,author_id,is_published)
        VALUES
        (
          'Article 1',
          'Sample article content 1',
          1,
          0
        ),
        (
          'Article 2',
          'Sample article content 2',
          1,
          1
        ),
        (
          'Article 3',
          'Sample article content 3',
          2,
          1
        )
      ;

      INSERT INTO numerics (
        numeric_col,
        decimal_col,
        int_col,
        smallint_col,
        float_col,
        real_col,
        bigint_col,
        tinyint_col
        ) VALUES ( 1.234
                 , 123.45
                 , 2147483647
                 , 3277
                 , 2.23E -308
                 , 1.18E - 38
                 , 9223372036854775807
                 , 254
                 )
      ;
