query MyQuery {
  getMovieById(movie_id: 1) {
    getActorsFromMovie {
      MovieFromActor {
        getActorsFromMovie {
          MovieFromActor {
            movie_id
            rating
          }
        }
      }
    }
  }
}