query MyQuery {
  where_does_john_hughes_work: InstitutionMany(
    where: { staff: { last_name: { _eq: "Hughes" } } }
  ) {
    id
    location {
      city
      campuses
    }
  }

  where_has_staff_with_a_dog: InstitutionMany(
    where: { staff: { pets: { name: { _eq: "Dog" } } } }
  ) {
    id
    location {
      city
      campuses
    }
  }

  institution_in_a_country_with_a_city_named_stockholm: InstitutionMany(
    where: { location: { country: { cities: { name: { _eq: "Stockholm" } } } } }
  ) {
    id
    location {
      country {
        cities {
          name
        }
      }
    }
  }
}
