query {
  Institution_aggregate {
    Location {
      _count
      City {
        _min
        _max
      }
      Country {
        min_country: _min
        max_country: _max
      }
    }
    count_all: _count
  }
}
