# Example audit config file
#
# It may be located in the user home (`~/.cargo/audit.toml`) or in the project
# root (`.cargo/audit.toml`).
#
# All of the options which can be passed via CLI arguments can also be
# permanently specified in this file.

[advisories]
ignore = ["RUSTSEC-2024-0437"] # advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]

# RUSTSEC-2024-0437
#
# https://github.com/tikv/rust-prometheus/issues/538#issuecomment-2708222613
# we ignore this there is no current fix, and because the prometheus crate 
# that uses protobuf does not parse any protobufs, only writes them.
