# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Specify additional command line arguments
#
# - arguments: [--color, --cpp-simple, -XQuasiQuotes]

- arguments: -XQuasiQuotes

# Control which extensions/flags/modules/functions can be used
#
# - extensions:
#   - default: false # all extension are banned by default
#   - name: [PatternGuards, ViewPatterns] # only these listed extensions can be used
#   - {name: CPP, within: CrossPlatform} # CPP can only be used in a given module
#
# - flags:
#   - {name: -w, within: []} # -w is allowed nowhere
#
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules


# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}

# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# Generalise map to fmap, ++ to <>
# - group: {name: generalise, enabled: true}


# Ignore some builtin hints
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules

- ignore: {name: Reduce duplication}
- ignore: {name: Redundant $}
- ignore: {name: Redundant bracket}
- ignore: {name: Use fmap}
- ignore: {name: Use first}
- ignore: {name: Use if}
- ignore: {name: Redundant <$>}
- ignore: {name: Use ++}
- ignore: {name: Use const}
- ignore: {name: Eta reduce}
- ignore: {name: Redundant multi-way if}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use bimap}
- ignore: {name: Use $>}
- ignore: {name: Use <$>}
- ignore: {name: "Use ?~"}
- ignore: {name: Use <=<}
- ignore: {name: Use sequenceA}
- ignore: {name: Use camelCase}
- ignore: {name: Redundant return}
- ignore: {name: Use <$>, within: [Hasura.RQL.DDL.Metadata, Hasura.Backends.MSSQL.Types.Instances]}
- ignore: {name: Functor law, within: Hasura.Server.AuthSpec}
- ignore: {name: Use underscore} # suggests to format port numbers

# Define some custom infix operators
# - fixity: infixr 3 ~^#^~


# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml


- group:
    name: hasura-prelude
    enabled: true
    imports:
    - package base
    rules:
    - warn: {lhs: "a == []", rhs: "null a"}
    - warn: {lhs: "a /= []", rhs: "not (null a)"}
    - warn: {lhs: "maybe b return a", rhs: "onNothing a b"}
    - warn: {lhs: "maybe b pure a", rhs: "onNothing a b"}
    - warn: {lhs: "maybe (return ()) b a", rhs: "onJust a b"}
    - warn: {lhs: "maybe (pure ()) b a", rhs: "onJust a b"}
    - warn: {lhs: "either b return a", rhs: "onLeft a b"}
    - warn: {lhs: "either b pure a", rhs: "onLeft a b"}
    - warn: {lhs: "maybe (f x) f", rhs: "f . fromMaybe x"}
    - warn: {lhs: "maybe (f x) f", rhs: "f . fromMaybe x"}
    - warn: {lhs: "either (f . g) (f . h)", rhs: "f . either g h"}
    - warn: {lhs: "either (f . g) (f . h)", rhs: "f . either g h"}
    - warn: {lhs: "onNothing x (return y)", rhs: "return (fromMaybe y x)"}
    - warn: {lhs: "onNothing x (pure y)", rhs: "pure (fromMaybe y x)"}
    - warn: {lhs: "onLeft x (return . f)", rhs: "return (either f id x)"}
    - warn: {lhs: "onLeft x (pure . f)", rhs: "pure (either f id x)"}
    - warn: {lhs: "case x of {Right a -> pure a; Left c -> d}", rhs: "onLeft x (\\ c -> d)"}
    - warn: {lhs: "case x of {Left c -> d; Right a -> pure a}", rhs: "onLeft x (\\ c -> d)"}
    - warn: {lhs: "case x of {Right a -> return a; Left c -> d}", rhs: "onLeft x (\\ c -> d)"}
    - warn: {lhs: "case x of {Left c -> d; Right a -> return a}", rhs: "onLeft x (\\ c -> d)"}
    - warn: {lhs: "case x of {Nothing -> a; Just b -> pure b}", rhs: "onNothing x a"}
    - warn: {lhs: "case x of {Just b -> pure b; Nothing -> a}", rhs: "onNothing x a"}
    - warn: {lhs: "case x of {Nothing -> a; Just b -> return b}", rhs: "onNothing x a"}
    - warn: {lhs: "case x of {Just b -> return b; Nothing -> a}", rhs: "onNothing x a"}
    - warn: {lhs: "if x then pure (); else y", rhs: "unless x y"}
    - warn: {lhs: "if x then return (); else y", rhs: "unless x y"}
    - warn: {lhs: "if x then y; else pure ()", rhs: "when x y"}
    - warn: {lhs: "if x then y; else return ()", rhs: "when x y"}
    - warn: {lhs: "unless (not x)", rhs: "when x"}
    - warn: {lhs: "when (not x)", rhs: "unless x"}
    - suggest: {lhs: "not x && not y", rhs: "not (x || y)"}
    - suggest: {lhs: "not x || not y", rhs: "not (x && y)"}
    - warn: {lhs: "Data.Text.pack (Prelude.show x)", rhs: "Hasura.Prelude.tshow x"}
    - warn: {lhs: "map f xs == map f ys",   rhs: "liftEq ((==) `on` f)", note: "This is liable to be faster"}
    - suggest: {lhs: "fmap f xs == fmap f ys", rhs: "liftEq ((==) `on` f)", note: "This is liable to be faster"}
    # mapKeys:
    - warn: {lhs: "Data.HashMap.Strict.Extended.fromList . map (first f) . Data.HashMap.Strict.Extended.toList", rhs: "mapKeys f"}
    - warn: {lhs: "Data.HashMap.Strict.fromList . map (first f) . Data.HashMap.Strict.toList", rhs: "mapKeys f"}
    - warn: {lhs: "Data.HashMap.Strict.Extended.fromList $ map (first f) $ Data.HashMap.Strict.Extended.toList x", rhs: "mapKeys f x"}
    - warn: {lhs: "Data.HashMap.Strict.fromList $ map (first f) $ Data.HashMap.Strict.toList x", rhs: "mapKeys f x"}
    # MaybeT
    - warn: {lhs: "MaybeT (pure x)",         rhs: "hoistMaybe x"}
    - warn: {lhs: "MaybeT (return x)",       rhs: "hoistMaybe x"}
    - warn: {lhs: "MaybeT (pure Nothing)",   rhs: "Control.Applicative.empty"}
    - warn: {lhs: "MaybeT (return Nothing)", rhs: "Control.Applicative.empty"}
    # catMaybes
    - warn: {lhs: "Data.HashMap.Strict.mapMaybe id", rhs: "Data.HashMap.Strict.Extended.catMaybes"}
    - warn: {lhs: "Data.HashMap.Strict.Extended.mapMaybe id", rhs: "Data.HashMap.Strict.Extended.catMaybes"}
    - warn: {lhs: "Data.HashMap.Strict.InsOrd.mapMaybe id", rhs: "Data.HashMap.Strict.InsOrd.Extended.catMaybes"}
    - warn: {lhs: "Data.HashMap.Strict.InsOrd.Extended.mapMaybe id", rhs: "Data.HashMap.Strict.InsOrd.Extended.catMaybes"}
    - warn: {lhs: "Data.IntMap.Strict.mapMaybe id", rhs: "Data.HashMap.Strict.Extended.catMaybes"}
    - warn: {lhs: "Data.IntMap.Strict.Extended.mapMaybe id", rhs: "Data.HashMap.Strict.Extended.catMaybes"}

- group:
    name: data-text-extended
    enabled: true
    imports:
    - package base
    rules:
    - warn: {lhs: "Data.Text.intercalate \", \" x", rhs: "commaSeparated x", note: "From Data.Text.Extended"}
    - warn: {lhs: "Data.Text.Extended.intercalate \", \" x", rhs: "commaSeparated x"}

- group:
    name: mssql-transaction
    enabled: true
    imports:
    - package base
    rules:
    - warn: {lhs: "Database.MSSQL.runTxE id tx pool", rhs: "Database.MSSQL.runTx tx pool"}
    - warn: {lhs: "Database.MSSQL.unitQueryE id q", rhs: "Database.MSSQL.unitQuery q"}
    - warn: {lhs: "Database.MSSQL.singleRowQueryE id tx pool", rhs: "Database.MSSQL.singleRowQuery tx pool"}
    - warn: {lhs: "Database.MSSQL.multiRowQueryE id tx pool", rhs: "Database.MSSQL.multiRowQuery tx pool"}

- group:
    name: unsafe
    enabled: true
    imports:
      - package base
    rules:
      - suggest: {lhs: "Language.GraphQL.Draft.Syntax.unsafeMkName", rhs: "Language.GraphQL.Draft.Syntax.mkName", note: "avoid unsafeMkName if possible"}
