[package]
name = "tracing-util"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
derive_more = { workspace = true }
http = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-contrib = { workspace = true }
opentelemetry-http = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry-stdout = { workspace = true }
opentelemetry-zipkin = { workspace = true }
opentelemetry_sdk = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
axum = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
  "axum", # used in doc examples
]

[lints]
workspace = true
