const shadows = {
  "--ifm-global-shadow-lw": "0 1px 2px 0 rgba(0,0,0,.1)",
  "--ifm-global-shadow-md": "0 5px 40px rgba(0,0,0,.2)",
  "--ifm-global-shadow-tl": "0 12px 28px 0 rgba(0,0,0,.2),0 2px 4px 0 rgba(0,0,0,.1)",
  "--ifm-blockquote-shadow": "none",
}

const colorValues = {
  "--ifm-dark-value": "10%",
  "--ifm-darker-value": "15%",
  "--ifm-darkest-value": "30%",
  "--ifm-light-value": "15%",
  "--ifm-lighter-value": "30%",
  "--ifm-lightest-value": "50%",
  "--ifm-contrast-background-value": "90%",
  "--ifm-contrast-foreground-value": "70%",
  "--ifm-contrast-background-dark-value": "70%",
  "--ifm-contrast-foreground-dark-value": "90%",
}

const colors = {
  "--ifm-hover-overlay": "rgba(0,0,0,.05)",
  "--ifm-color-primary": "#33bddb",
  "--ifm-color-secondary": "#ebedf0",
  "--ifm-color-success": "#00a400",
  "--ifm-color-info": "#54c7ec",
  "--ifm-color-warning": "#ffba00",
  "--ifm-color-danger": "#fa383e",
  "--ifm-color-primary-dark": "#209db8",
  "--ifm-color-primary-darker": "#1c89a1",
  "--ifm-color-primary-darkest": "#18758a",
  "--ifm-color-primary-light": "#61cce3",
  "--ifm-color-primary-lighter": "#78d3e7",
  "--ifm-color-primary-lightest": "#8fdbeb",
  "--ifm-color-primary-contrast-background": "#ebf2fc",
  "--ifm-color-primary-contrast-foreground": "#102445",
  "--ifm-color-secondary-dark": "#d4d5d8",
  "--ifm-color-secondary-darker": "#c8c9cc",
  "--ifm-color-secondary-darkest": "#a4a6a8",
  "--ifm-color-secondary-light": "#eef0f2",
  "--ifm-color-secondary-lighter": "#f1f2f5",
  "--ifm-color-secondary-lightest": "#f5f6f8",
  "--ifm-color-secondary-contrast-background": "#fdfdfe",
  "--ifm-color-secondary-contrast-foreground": "#474748",
  "--ifm-color-success-dark": "#009400",
  "--ifm-color-success-darker": "#008b00",
  "--ifm-color-success-darkest": "#007300",
  "--ifm-color-success-light": "#26b226",
  "--ifm-color-success-lighter": "#4dbf4d",
  "--ifm-color-success-lightest": "#80d280",
  "--ifm-color-success-contrast-background": "#e6f6e6",
  "--ifm-color-success-contrast-foreground": "#003100",
  "--ifm-color-info-dark": "#4cb3d4",
  "--ifm-color-info-darker": "#47a9c9",
  "--ifm-color-info-darkest": "#3b8ba5",
  "--ifm-color-info-light": "#6ecfef",
  "--ifm-color-info-lighter": "#87d8f2",
  "--ifm-color-info-lightest": "#aae3f6",
  "--ifm-color-info-contrast-background": "#eef9fd",
  "--ifm-color-info-contrast-foreground": "#193c47",
  "--ifm-color-warning-dark": "#e6a700",
  "--ifm-color-warning-darker": "#d99e00",
  "--ifm-color-warning-darkest": "#b38200",
  "--ifm-color-warning-light": "#ffc426",
  "--ifm-color-warning-lighter": "#ffcf4d",
  "--ifm-color-warning-lightest": "#ffdd80",
  "--ifm-color-warning-contrast-background": "#fff8e6",
  "--ifm-color-warning-contrast-foreground": "#4d3800",
  "--ifm-color-danger-dark": "#e13238",
  "--ifm-color-danger-darker": "#d53035",
  "--ifm-color-danger-darkest": "#af272b",
  "--ifm-color-danger-light": "#fb565b",
  "--ifm-color-danger-lighter": "#fb7478",
  "--ifm-color-danger-lightest": "#fd9c9f",
  "--ifm-color-danger-contrast-background": "#ffebec",
  "--ifm-color-danger-contrast-foreground": "#4b1113",
  "--ifm-color-white": "#fff",
  "--ifm-color-black": "#000",
  "--ifm-color-gray-100": "#f5f6f7",
  "--ifm-color-gray-200": "#ebedf0",
  "--ifm-color-gray-300": "#dadde1",
  "--ifm-color-gray-400": "#ccd0d5",
  "--ifm-color-gray-500": "#bec3c9",
  "--ifm-color-gray-600": "#8d949e",
  "--ifm-color-gray-700": "#606770",
  "--ifm-color-gray-800": "#444950",
  "--ifm-color-gray-900": "#1c1e21",
  "--ifm-color-content-secondary": "#525860",
  "--ifm-background-color": "transparent",
  "--ifm-code-background": "#f6f7f8",
  "--ifm-pre-color": "inherit",
  "--ifm-heading-color": "inherit",
  "--ifm-table-background": "transparent",
  "--ifm-table-head-background": "inherit",
  "--ifm-table-head-color": "inherit",
  "--ifm-table-cell-color": "inherit",
  "--ifm-scrollbar-track-background-color": "#f1f1f1",
  "--ifm-scrollbar-thumb-background-color": "silver",
  "--ifm-scrollbar-thumb-hover-background-color": "#a7a7a7",
  "--ifm-alert-background-color": "inherit",
  "--ifm-alert-border-color": "inherit",
  "--collapse-button-bg-color-dark": "#2e333a",
  "--ifm-footer-color": "inherit",
};

const fonts = {
  "--ifm-font-family-base": "system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol'",
  "--ifm-font-family-monospace": "SFMono-Regular,Menlo,Monaco,Consolas,'Liberation Mono','Courier New',monospace",
  "--ifm-font-size-base": "100%",
  "--ifm-font-weight-light": "300",
  "--ifm-font-weight-normal": "400",
  "--ifm-font-weight-semibold": "500",
  "--ifm-font-weight-bold": "700",
  "--ifm-line-height-base": "1.65",
  "--ifm-code-font-size": "95%",
  "--ifm-pre-line-height": "1.45",
  "--ifm-heading-line-height": "1.25",
  "--ifm-h1-font-size": "2rem",
  "--ifm-h2-font-size": "1.5rem",
  "--ifm-h3-font-size": "1.25rem",
  "--ifm-h4-font-size": "1rem",
  "--ifm-h5-font-size": "0.875rem",
  "--ifm-h6-font-size": "0.85rem",
};

const spacings = {
  "--ifm-global-border-width": "1px",
  "--ifm-global-radius": "0.4rem",
  "--ifm-global-spacing": "1rem",
  "--ifm-footer-link-horizontal-spacing": "0.5rem",
  "--ifm-footer-title-color": "inherit",
  "--ifm-menu-link-padding-horizontal": "1rem",
  "--ifm-menu-link-padding-vertical": "0.375rem",
  "--ifm-menu-link-sublist-icon-filter": "none",
  "--ifm-navbar-height": "3.75rem",
  "--ifm-navbar-item-padding-horizontal": "0.75rem",
  "--ifm-navbar-item-padding-vertical": "0.25rem",
  "--ifm-navbar-sidebar-width": "83vw",
  "--ifm-pills-spacing": "0.0625rem",
  "--ifm-tabs-padding-horizontal": "1rem",
  "--ifm-tabs-padding-vertical": "1rem",
  "--ifm-tabs-spacing": "0.0625rem",
  "--docusaurus-announcement-bar-height": "auto",
  "--doc-sidebar-width": "300px",
  "--doc-sidebar-hidden-width": "30px",
  "--ifm-hr-border-width": "1px",
  "--ifm-hr-margin-vertical": "1.5rem",
  "--ifm-scrollbar-size": "7px",
  "--ifm-image-alignment-padding": "1.25rem",
  "--ifm-leading-desktop": "1.25",
  "--ifm-list-left-padding": "2rem",
  "--ifm-list-margin": "1rem",
  "--ifm-list-item-margin": "0.25rem",
  "--ifm-list-paragraph-margin": "1rem",
  "--ifm-table-cell-padding": "0.75rem",
  "--ifm-container-width": "1140px",
  "--ifm-container-width-xl": "1320px",
  "--ifm-code-padding-horizontal": "0.1rem",
  "--ifm-code-padding-vertical": "0.1rem",
  "--ifm-pre-padding": "1rem",
  "--ifm-heading-margin-top": "0",
  "--ifm-table-border-width": "1px",
  "--ifm-alert-border-width": "0px",
  "--ifm-alert-border-left-width": "5px",
  "--ifm-blockquote-border-left-width": "2px",
  "--ifm-blockquote-padding-vertical": "0",
  "--ifm-button-padding-horizontal": "1.5rem",
  "--ifm-button-padding-vertical": "0.375rem",
  "--ifm-button-size-multiplier": "1",
  "--ifm-button-group-margin": "2px",
  "--ifm-toc-padding-vertical": "0.5rem",
  "--ifm-toc-padding-horizontal": "0.5rem",
};

const misc = {
  "--ifm-z-index-dropdown": "10",
  "--ifm-z-index-fixed": "11",
  "--ifm-z-index-overlay": "13",
};

const search = {
  "--docsearch-primary-color": "#5468ff",
  "--docsearch-text-color": "#1c1e21",
  "--docsearch-spacing": "12px",
  "--docsearch-icon-stroke-width": "1.4",
  "--docsearch-muted-color": "#969faf",
  "--docsearch-container-background": "rgba(101,108,133,.8)",
  "--docsearch-logo-color": "#5468ff",
  "--docsearch-modal-width": "560px",
  "--docsearch-modal-height": "600px",
  "--docsearch-modal-background": "#f5f6f7",
  "--docsearch-modal-shadow": "inset 1px 1px 0 0 hsla(0,0%,100%,.5),0 3px 8px 0 #555a64",
  "--docsearch-searchbox-height": "56px",
  "--docsearch-searchbox-background": "#ebedf0",
  "--docsearch-searchbox-focus-background": "#fff",
  "--docsearch-hit-height": "56px",
  "--docsearch-hit-color": "#444950",
  "--docsearch-hit-active-color": "#fff",
  "--docsearch-hit-background": "#fff",
  "--docsearch-hit-shadow": "0 1px 3px 0 #d4d9e1",
  "--docsearch-key-gradient": "linear-gradient(-225deg,#d5dbe4,#f8f8f8)",
  "--docsearch-key-shadow": "inset 0 -2px 0 0 #cdcde6,inset 0 0 1px 1px #fff,0 1px 2px 1px rgba(30,35,90,.4)",
  "--docsearch-footer-height": "44px",
  "--docsearch-footer-background": "#fff",
  "--docsearch-footer-shadow": "0 -1px 0 0 #e0e3e8,0 -3px 6px 0 rgba(69,98,155,.12)",
}

const darkSearch =  {
  "--docsearch-text-color": "#f5f6f7",
  "--docsearch-container-background": "rgba(9,10,17,0.8)",
  "--docsearch-modal-background": "#15172a",
  "--docsearch-modal-shadow": "inset 1px 1px 0 0 #2c2e40,0 3px 8px 0 #000309",
  "--docsearch-searchbox-background": "#090a11",
  "--docsearch-searchbox-focus-background": "#000",
  "--docsearch-hit-color": "#bec3c9",
  "--docsearch-hit-shadow": "none",
  "--docsearch-hit-background": "#090a11",
  "--docsearch-key-gradient": "linear-gradient(-26.5deg,#565872,#31355b)",
  "--docsearch-key-shadow": "inset 0 -2px 0 0 #282d55,inset 0 0 1px 1px #51577d,0 2px 2px 0 rgba(3,4,9,0.3)",
  "--docsearch-footer-background": "#1e2136",
  "--docsearch-footer-shadow": "inset 0 1px 0 0 rgba(73,76,106,0.5),0 -4px 8px 0 rgba(0,0,0,0.2)",
  "--docsearch-logo-color": "#fff",
  "--docsearch-muted-color": "#7f8497",
}

const darkTheme =  {
  "--ifm-background-color": "#18191a",
  "--ifm-background-surface-color": "#242526",
  "--ifm-hover-overlay": "rgba(255, 255, 255, 0.05)",
  "--ifm-color-content-secondary": "rgba(255, 255, 255, 1)",
  "--ifm-breadcrumb-separator-filter": "invert(64%) sepia(11%) saturate(0%) hue-rotate(149deg) brightness(99%) contrast(95%)",
  "--ifm-code-background": "rgb(51, 52, 55)",
  "--ifm-scrollbar-track-background-color": "#444444",
  "--ifm-scrollbar-thumb-background-color": "#686868",
  "--ifm-scrollbar-thumb-hover-background-color": "#7a7a7a",
  "--ifm-color-primary-contrast-background": "rgb(16, 36, 69)",
  "--ifm-color-primary-contrast-foreground": "rgb(235, 242, 252)",
  "--ifm-color-secondary-contrast-background": "rgb(71, 71, 72)",
  "--ifm-color-secondary-contrast-foreground": "rgb(253, 253, 254)",
  "--ifm-color-success-contrast-background": "rgb(0, 49, 0)",
  "--ifm-color-success-contrast-foreground": "rgb(230, 246, 230)",
  "--ifm-color-info-contrast-background": "rgb(25, 60, 71)",
  "--ifm-color-info-contrast-foreground": "rgb(238, 249, 253)",
  "--ifm-color-warning-contrast-background": "rgb(77, 56, 0)",
  "--ifm-color-warning-contrast-foreground": "rgb(255, 248, 230)",
  "--ifm-color-danger-contrast-background": "rgb(75, 17, 19)",
  "--ifm-color-danger-contrast-foreground": "rgb(255, 235, 236) ",
}

export const cssVars = { colorValues, colors, fonts, spacings, shadows, darkTheme, search, darkSearch, misc };