query MyQuery {
  Track(where: { AlbumRemote: { Title: { _eq: "Restless and Wild" } } }) {
    AlbumId
    Name
    AlbumRemote {
      Title
    }
  }
  TrackWithoutRelationshipField: Track(
    where: { AlbumRemote: { Title: { _eq: "Restless and Wild" } } }
  ) {
    Name
  }
  TrackAnd: Track(
    where: {
      _and: [
        { AlbumRemote: { Title: { _eq: "Restless and Wild" } } }
        { AlbumId: { _eq: 3 } }
      ]
    }
  ) {
    AlbumId
    Name
    AlbumRemote {
      Title
    }
  }
  TrackOr: Track(
    where: {
      _or: [
        { AlbumRemote: { Title: { _eq: "Restless and Wild" } } }
        { AlbumId: { _eq: 2 } }
      ]
    }
  ) {
    AlbumId
    Name
    AlbumRemote {
      Title
    }
  }
}
