query RemoteJoinsCandidateQuery2 {
  MovieMany(where: { rating: { _eq: 4 } }) {
    id
    title
    rating
    Analytics(limit: 5, order_by: [{ analytics_id: Asc }]) {
      id
      num_users_faved
      num_views_day
      total_votes
      Movie {
        title
        Actors {
          name
        }
        Analytics {
          id
          total_votes
        }
      }
    }
  }
}
