type: bulk
args:
- type: run_sql
  args:
    sql: |
      DELETE FROM article;
      SELECT setval('article_id_seq', 1, FALSE);
      DELETE FROM "author details";
      SELECT setval('"author details_id_seq"', 1, FALSE);
