query MyQuery {
  Track(where: { Album: { Title: { _eq: "Restless and Wild" } } }) {
    TrackId
    AlbumId
    Name
    Album {
      Title
    }
  }
  TrackWithoutRelationshipField: Track(
    where: { Album: { Title: { _eq: "Restless and Wild" } } }
  ) {
    TrackId
    Name
  }
  TrackAnd: Track(
    where: {
      _and: [
        { Album: { Title: { _eq: "Restless and Wild" } } }
        { AlbumId: { _eq: 3 } }
      ]
    }
  ) {
    TrackId
    AlbumId
    Name
    Album {
      Title
    }
  }
  TrackOr: Track(
    where: {
      _or: [
        { Album: { Title: { _eq: "Restless and Wild" } } }
        { AlbumId: { _eq: 2 } }
      ]
    }
  ) {
    TrackId
    AlbumId
    Name
    Album {
      Title
    }
  }
}
