"""
Django settings for helloworld project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$*ed_#&bh5x$a_79x=xr##egg)40)s7n+)8a1m)j$up688k-ib'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# -------------------- HASURA customization ----------------------------- #
# HASURA: We do not need to use the auth and session apps while building on
# Hasura.  Because Hasura already provides Auth APIs for authentication and
# sessions. Also disable all the apps requiring a database. You can enable the
# other apps except auth and sessions - but for that you also have to configure
# the DATABASES section which is also disabled by default.
# Application definition
INSTALLED_APPS = [
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    # 'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'django.contrib.staticfiles',
]

# -------------------- HASURA customization ----------------------------- #
# HASURA: We do not need to use the auth and session middlewares while building
# on Hasura.  Because Hasura already provides Auth APIs for authentication and
# sessions.
# Disabled the message middleware also because this app is disabled and we are
# not using any DB.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helloworld.urls'

# -------------------- HASURA customization ----------------------------- #
# HASURA: We do not need to use the auth and session middlewares while building
# on Hasura. Hence disable auth and messages template context processors
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'helloworld.wsgi.application'


# -------------------- HASURA customization ----------------------------- #
# HASURA: We do not need to use the DB component while building on Hasura.
# Because Hasura already provides Data APIs. Hence disable the DATABASES in
# django
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# -------------------- HASURA customization ----------------------------- #
# HASURA: We do not need to use the password validators while building on
# Hasura. We are going to use the Auth APIs.
# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

