[package]
name = "metadata-schema-generator"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "metadata-schema-generator"
path = "src/main.rs"
bench = false

[dependencies]
open-dds = { path = "../open-dds" }

serde_json = { workspace = true }
schemars = { workspace = true }
