apiVersion: v1
entries:
  graphql-engine:
  - apiVersion: v2
    appVersion: 1.3.2
    created: "2020-09-12T23:05:44.8436107+08:00"
    dependencies:
    - condition: hasura.database.postgres.managed.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.4.1
    description: A Helm chart for Hasura GraphQL Engine. Currently in alpha
    digest: 8314db6acd9688d069760f56868e6e6c036b80af9d42879ecc09f55c924f0425
    keywords:
    - application
    - graphql
    - haskell
    - hasura
    - productivity
    - web
    maintainers:
    - email: 29133953+stevefan1999-personal@users.noreply.github.com
      name: Steve Fan
    name: graphql-engine
    type: application
    urls:
    - graphql-engine-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 1.3.2
    created: "2020-09-12T23:05:44.8396108+08:00"
    description: A Helm chart for Hasura GraphQL Engine. Currently in alpha
    digest: fafbc4154af38b85f635dc8b9daf800e39f7777b5007ea145561e0f9a1ff68c7
    keywords:
    - application
    - graphql
    - haskell
    - hasura
    - productivity
    - web
    maintainers:
    - email: 29133953+stevefan1999-personal@users.noreply.github.com
      name: Steve Fan
    name: graphql-engine
    type: application
    urls:
    - graphql-engine-0.0.5.tgz
    version: 0.0.5
generated: "2020-09-12T23:05:44.8366108+08:00"
