apiVersion: v1
entries:
  graphql-engine:
  - apiVersion: v1
    appVersion: 1.3.2
    created: "2020-09-12T22:42:37.7362527+08:00"
    description: A Helm chart for Hasura GraphQL Engine. Currently in alpha
    digest: fafbc4154af38b85f635dc8b9daf800e39f7777b5007ea145561e0f9a1ff68c7
    keywords:
    - application
    - graphql
    - haskell
    - hasura
    - productivity
    - web
    maintainers:
    - email: 29133953+stevefan1999-personal@users.noreply.github.com
      name: Steve Fan
    name: graphql-engine
    type: application
    urls:
    - graphql-engine-0.0.5.tgz
    version: 0.0.5
generated: "2020-09-12T22:42:37.732252+08:00"
