import { FrequentlyUsedColumn } from '../../types';
import { PostgresTable } from '../types';

/** Presets shared by Postgres-family drivers; each driver appends its own
 *  `updated_at` preset since its trigger SQL is dialect-specific. */
export const commonFrequentlyUsedColumns: FrequentlyUsedColumn[] = [
  {
    name: 'id',
    validFor: ['add'],
    type: 'serial',
    typeText: 'integer (auto-increment)',
    primary: true,
  },
  {
    name: 'id',
    validFor: ['add'],
    type: 'bigserial',
    typeText: 'bigint (auto-increment)',
    primary: true,
  },
  {
    name: 'id',
    validFor: ['add'],
    type: 'int GENERATED BY DEFAULT AS IDENTITY',
    typeText: 'int (identity, generated by default)',
    primary: true,
    minPGVersion: 10,
  },
  {
    name: 'id',
    validFor: ['add'],
    type: 'uuid',
    typeText: 'UUID',
    primary: true,
    default: 'gen_random_uuid()',
  },
  {
    name: 'created_at',
    validFor: ['add', 'modify'],
    type: 'timestamptz',
    typeText: 'timestamp',
    default: 'now()',
  },
];

export const getFrequentlyUsedColumns = (): FrequentlyUsedColumn[] => [
  ...commonFrequentlyUsedColumns,
  {
    name: 'updated_at',
    validFor: ['add', 'modify'],
    type: 'timestamptz',
    typeText: 'timestamp',
    default: 'now()',
    defaultText: 'now() + trigger to set value on update',
    dependentSQLGenerator: (table, columnName) => {
      const { schema: schemaName, name: tableName } = table as PostgresTable;
      const upSql = `
CREATE OR REPLACE FUNCTION "${schemaName}"."set_current_timestamp_${columnName}"()
RETURNS TRIGGER AS $$
DECLARE
  _new record;
BEGIN
  _new := NEW;
  _new."${columnName}" = NOW();
  RETURN _new;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER "set_${schemaName}_${tableName}_${columnName}"
BEFORE UPDATE ON "${schemaName}"."${tableName}"
FOR EACH ROW
EXECUTE PROCEDURE "${schemaName}"."set_current_timestamp_${columnName}"();
COMMENT ON TRIGGER "set_${schemaName}_${tableName}_${columnName}" ON "${schemaName}"."${tableName}"
IS 'trigger to set value of column "${columnName}" to current timestamp on row update';
`;

      const downSql = `DROP TRIGGER IF EXISTS "set_${schemaName}_${tableName}_${columnName}" ON "${schemaName}"."${tableName}";`;

      return {
        upSql,
        downSql,
      };
    },
  },
];
