query MyQuery {
  Album(limit: 2) {
    Tracks {
      TrackId
      Name
      Album {
        Title
      }
    }
  }

  Track(limit: 10) {
    TrackId
    Name
    Album {
      AlbumId
      Title
      ArtistId
    }
  }
}
