mutation MyMutation {
  addMovieWithGenres(
    movie: {
      movie_id: 111
      title: "MyMovie"
      genres: [
        { genre_id: 1, name: "horror" }
        { genre_id: 2, name: "thriller" }
      ]
    }
  ) {
    movie_id
    title
    rating
    genres {
      genre_id
      name
    }
  }
}
