apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hasura-graphql-engine.fullname" . }}
  labels:
    {{- include "hasura-graphql-engine.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.hasura -}}
  {{- with .secret -}}
    {{- if .jwt }}
  jwt: {{ .jwt | b64enc | quote }}
    {{- end }}

    {{- if .admin }}
  admin: {{ .admin | b64enc | quote }}
    {{- end }}
  {{- end -}}

  {{- with .database.postgres }}
  {{- if not .managed.enabled }}
  postgresql-password: {{ .external.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
