type: bulk
args:

- type: run_sql
  args:
    sql: |

      delete from article;
      SELECT setval('article_id_seq', 1, FALSE);

      delete from author;
      SELECT setval('author_id_seq', 1, FALSE);

      delete from resident;
      SELECT setval('resident_id_seq', 1, FALSE);

      delete from "user";
      SELECT setval('"user_id_seq"', 1, FALSE);

      delete from "account";
      SELECT setval('"account_id_seq"', 1, FALSE);
