query {
  __schema {
    queryType {
      name
      fields {
        name
        args {
          name
          defaultValue
          type {
            kind
            name
            ofType {
              kind
              name
            }
          }
        }
      }
    }
  }
  actor_type_name_query: __type(name: "Actor_bool_exp") {
    name
    kind
    inputFields {
      name
      type {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
            }
          }
        }
      }
    }
  }
  int_type_name_query: __type(name: "Int_Comparison_Exp") {
    name
    kind
    inputFields {
      name
      type {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
            }
          }
        }
      }
    }
  }
}
