{
 "title": "Hasura OpenTelemetry",
 "description": "Hasura GraphQL Engine dashboards for monitoring OpenTelemetry exporter",
 "tags": [ "hasura" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Sent Trace Spans",
   "type": "stat",
   "description": "Total number of exported trace spans",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_otel_sent_spans{instance=~\"$instance\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "SUM(increase(hasura_otel_dropped_spans{instance=~\"$instance\",job=~\"$job\"}[$__range]))",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "Total Sent Logs",
   "type": "stat",
   "description": "Total number of exported log lines",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_otel_sent_logs{job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "SUM(increase(hasura_otel_dropped_logs{job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Dropped"
    }
   ]
  },
  { "title": "Sent Trace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Success Sent Spans",
   "type": "timeseries",
   "description": "The rate of successfully exported trace spans",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_otel_sent_spans{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Sent Spans",
   "type": "timeseries",
   "description": "Total number of trace spans dropped due to sent failure",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_otel_dropped_spans{job=~\"$job\",instance=~\"$instance\",reason=\"send_failed\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped High Volume Spans",
   "type": "timeseries",
   "description": "Total number of trace spans dropped due to high trace volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_otel_dropped_spans{job=~\"$job\",instance=~\"$instance\",reason=\"buffer_full\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sent Log Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Success Sent Logs",
   "type": "timeseries",
   "description": "Total number of successfully exported log lines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_otel_sent_logs{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Sent Logs",
   "type": "timeseries",
   "description": "Total number of log lines dropped due to sent failure",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_otel_dropped_logs{job=~\"$job\",instance=~\"$instance\",reason=\"send_failed\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped High Volume Logs",
   "type": "timeseries",
   "description": "Total number of log lines dropped due to high trace volume",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_otel_dropped_logs{job=~\"$job\",instance=~\"$instance\",reason=\"buffer_full\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}