{
 "title": "Hasura HTTP GraphQL",
 "description": "Hasura dashboards for HTTP GraphQL requests",
 "tags": [ "hasura" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   },
   { "name": "operation_type", "label": "Operation Type", "query": "query,mutation" },
   {
    "name": "operation_name",
    "label": "Operation Name",
    "query": {
     "query": "label_values(hasura_graphql_requests_total{job=~\"$job\", instance=~\"$instance\", operation_type=~\"$operation_type\"},operation_name)"
    }
   },
   {
    "name": "query_hash",
    "label": "Query Hash",
    "query": {
     "query": "label_values(hasura_graphql_requests_total{job=~\"$job\", instance=~\"$instance\", operation_type=~\"$operation_type\", operation_name=~\"$operation_name\"},parameterized_query_hash)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Queries",
   "type": "stat",
   "description": "Number of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"query\",instance=~\"$instance\",job=~\"$job\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\", response_status=\"success\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"query\",job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Query Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Total Mutations",
   "type": "stat",
   "description": "Number of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"mutation\",job=~\"$job\",instance=~\"$instance\", response_status=\"success\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"mutation\",job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mutation Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Top Queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (job,operation_name,parameterized_query_hash) (increase(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\",operation_type=\"query\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Mutations",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(10, sum by (job,operation_name,parameterized_query_hash) (increase(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\",operation_type=\"mutation\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Error Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, 1 - (sum by (job,operation_type, operation_name, parameterized_query_hash) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\",response_status=\"success\"}[$__range])) / sum by (job,operation_type, operation_name, parameterized_query_hash) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__range]))))  > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GraphQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Query Request Rate",
   "type": "timeseries",
   "description": "The request rate of GraphQL Query requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (job, operation_name, parameterized_query_hash) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{operation_name}}"
    }
   ]
  },
  {
   "title": "Mutation Request Rate",
   "type": "timeseries",
   "description": "The request rate of GraphQL Mutation requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum by (job,operation_name, parameterized_query_hash) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\",operation_name=~\"$operation_name\",parameterized_query_hash=~\"$query_hash\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{operation_name}}"
    }
   ]
  },
  {
   "title": "Query Error Rate",
   "type": "timeseries",
   "description": "The error rate of GraphQL Query requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (job,operation_type, operation_name) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\",operation_name=~\"$operation_name\",response_status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{operation_name}}"
    }
   ]
  },
  {
   "title": "Mutation Error Rate",
   "type": "timeseries",
   "description": "The Error rate of GraphQL Query requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (job,operation_name,parameterized_query_hash) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\",operation_name=~\"$operation_name\",response_status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "{{job}} - {{operation_name}}"
    }
   ]
  },
  {
   "title": "Query Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__rate_interval])) by (job,instance,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutation Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__rate_interval])) by (job,instance,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "HTTP Connections",
   "type": "timeseries",
   "description": "Current number of active HTTP connections (excluding WebSocket connections)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (hasura_http_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Request Rate",
   "type": "timeseries",
   "description": "Total number of incoming requests for cache lookup",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_cache_request_count{job=~\"$job\",status=\"hit\"}[$__rate_interval]))",
     "legendFormat": "Cache Hit"
    },
    {
     "expr": "sum(rate(hasura_cache_request_count{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Data Transfer",
   "type": "timeseries",
   "description": "Data Transfer of HTTP Requests ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (increase(hasura_http_request_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + increase(hasura_http_response_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action Data Transfer",
   "type": "timeseries",
   "description": "Data Transfer of external action webhook requests ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (increase(hasura_action_request_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + increase(hasura_action_response_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}