module Data.Parser.URLTemplate (spec) where

import           Hasura.Prelude

import           Data.URL.Template
import           Test.Hspec
import           Test.QuickCheck

spec :: Spec
spec = describe "parseURLTemplate" $
  it "parse URL templates generated by printURLTemplate" $
    withMaxSuccess 50 $
    forAll (resize 10 genURLTemplate) $ \urlTemplate ->
    case parseURLTemplate (printURLTemplate urlTemplate) of
      Left err -> counterexample err False
      Right r  -> property $ r == urlTemplate
