---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-jwt-server
  name: auth-jwt-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-jwt-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: auth-jwt-server
    spec:
      containers:
      - image: hasura/base-git-image:0.7
        imagePullPolicy: IfNotPresent
        name: auth-jwt-server
        env:
        - name: DATABASE_URL
          value: postgres://postgres:@postgres.default:5432/postgres
        - name: PORT
          value: "8080"
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: customJwtSecret
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-jwt-server
  name: auth-jwt-server
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth-jwt-server
  type: ClusterIP
