---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-apollo
  name: react-apollo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-apollo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: react-apollo
    spec:
      containers:
      - image: hasura/base-git-image:0.7
        imagePullPolicy: IfNotPresent
        name: react-apollo
        env:
        - name: GATSBY_ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: algoliaAppId
        - name: GATSBY_ALGOLIA_SEARCH_KEY
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: algoliaSearchKey
        - name: ALGOLIA_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: algoliaAdminKey
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /graphql/react/introduction
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: react-apollo
  name: react-apollo
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: react-apollo
  type: ClusterIP
