query MyQuery {
  leonardoDiCaprio: getActorsByName(
    name_filter: { first_name: "Leonardo", surname: "DiCaprio" }
  ) {
    movie_id
    name
  }

  kate: getActorsByName(name_filter: { first_name: "Kate", surname: null }) {
    movie_id
    name
  }

  # This scenario is broken due to missing input properties not being coerced into nulls properly
  #   khan: getActorsByName(name_filter: { surname: "Khan" }) {
  #     movie_id
  #     name
  #   }
}
