[package]
name = "hasura-authn-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
bench = false

[dependencies]
engine-types = { path = "../../engine-types" }
open-dds = { path = "../../open-dds" }

axum = { workspace = true }
axum-core = { workspace = true }
derive_more = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
