[package]
name = "recursion_limit_macro"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true
bench = false

[dependencies]
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
