query MyQuery {
  match_london: InstitutionMany(
    where: { location: { city: { _eq: "London" } } }
  ) {
    id
    location {
      city
      campuses
    }
    location_country: location {
      country {
        name
      }
    }
    staff {
      last_name
      specialities
    }
    staff_first_name: staff {
      first_name
    }
    departments
  }

  match_uk: InstitutionMany(
    where: { location: { country: { name: { _eq: "UK" } } } }
  ) {
    id
    location {
      city
      campuses
    }
    location_country: location {
      country {
        name
      }
    }
    staff {
      last_name
      specialities
    }
    staff_first_name: staff {
      first_name
    }
    departments
  }

  match_two_nested_fields: InstitutionMany(
    where: {
      songs: {
        primaryAnthemTrackId: { _eq: 2270 }
        secondaryAnthemTrackId: { _eq: 2271 }
      }
    }
  ) {
    id
    songs {
      primaryAnthemTrackId
      secondaryAnthemTrackId
    }
  }

  nested_logical_operators: InstitutionMany(
    where: {
      songs: {
        _or: [
          { primaryAnthemTrackId: { _eq: 2270 } }
          { primaryAnthemTrackId: { _eq: 3421 } }
        ]
      }
    }
  ) {
    id
    songs {
      primaryAnthemTrackId
      secondaryAnthemTrackId
    }
  }
}
