query MyQuery {
  match_london: InstitutionMany(
    where: { location: { city: { _eq: "London" } } }
  ) {
    id
    location {
      city
      campuses
    }
    location_country: location {
      country {
        name
      }
    }
    staff {
      last_name
      specialities
    }
    staff_first_name: staff {
      first_name
    }
    departments
  }

  match_uk: InstitutionMany(
    where: { location: { country: { name: { _eq: "UK" } } } }
  ) {
    id
    location {
      city
      campuses
    }
    location_country: location {
      country {
        name
      }
    }
    staff {
      last_name
      specialities
    }
    staff_first_name: staff {
      first_name
    }
    departments
  }
}
