description: User can query geometry values which satisfies filter in select permission
url: /v1/query
status: 200
headers:
  X-Hasura-Role: user1
response:
- id: 3
  type: linestring
  geom_col:
    type: LineString
    crs:
      type: name
      properties:
        name: urn:ogc:def:crs:EPSG::4326
    coordinates:
    - - 1
      - 0
    - - 0.5
      - 0.5
    - - 0
      - 1
- id: 4
  type: polygon
  geom_col:
    type: Polygon
    crs:
      type: name
      properties:
        name: urn:ogc:def:crs:EPSG::4326
    coordinates:
    - - - 0
        - 0
      - - 0
        - 1
      - - 1
        - 1
      - - 1
        - 0
      - - 0
        - 0
- id: 5
  type: polygon
  geom_col:
    type: Polygon
    crs:
      type: name
      properties:
        name: urn:ogc:def:crs:EPSG::4326
    coordinates:
    - - - 2
        - 0
      - - 2
        - 1
      - - 3
        - 1
      - - 3
        - 0
      - - 2
        - 0
query:
  type: select
  args:
    table: geom_table
    columns:
    - id
    - type
    - geom_col
