-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Todos exposing (created_at, id, is_completed, is_public, title, user, user_id)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


created_at : SelectionSet Hasura.ScalarCodecs.Timestamptz Hasura.Object.Todos
created_at =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created_at" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


id : SelectionSet Int Hasura.Object.Todos
id =
    Object.selectionForField "Int" "id" [] Decode.int


is_completed : SelectionSet Bool Hasura.Object.Todos
is_completed =
    Object.selectionForField "Bool" "is_completed" [] Decode.bool


is_public : SelectionSet Bool Hasura.Object.Todos
is_public =
    Object.selectionForField "Bool" "is_public" [] Decode.bool


title : SelectionSet String Hasura.Object.Todos
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| An object relationship
-}
user : SelectionSet decodesTo Hasura.Object.Users -> SelectionSet decodesTo Hasura.Object.Todos
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


user_id : SelectionSet String Hasura.Object.Todos
user_id =
    Object.selectionForField "String" "user_id" [] Decode.string
