settings:
  files:
    outputs:
      status: false
      name: outputs.log
    logs:
      status: false
      name: logs.log
    errors:
      status: false
      name: errors.log
  legacy:
    force: false
    interval: 100ms
server:
  status: false
  open: false
  port: 5001
  host: localhost
schema:
- name: hasura-graphql-engine
  path: cmd/hasura
  commands:
    install:
      status: true
      method: go install
  watcher:
    paths:
    - /
    - ../../
    extensions:
    - go
    ignored_paths:
    - ../../.git
    - ../../.realize
    - ../../vendor
    - ../../docs
    - ../../build
    - ../../vendor.orig
