name: "🚀 Feature request"
description: "Suggest an idea for improving Hasura"
title: "[Request]: "
labels: ["k/enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: "Is your proposal related to a problem?"
      description: "Provide a clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: "Describe alternatives you've considered"
      description: "Provide your answer here."
    validations:
      required: false
  - type: textarea
    id: pr
    attributes:
      label: "If the feature is approved, would you be willing to submit a PR?"
      description: "Provide your answer here."
    validations:
      required: false
