query {
  # this is fallible non-null command field
  getActorById(actor_id: 1) {
    name
    Movies {
      title
    }
  }

  AuthorMany(order_by: [{ author_id: Desc }]) {
    author_id
    first_name
  }

  MovieMany {
    title
    rating
  }
}
