query MyQuery {
  InstitutionMany {
    staff {
      last_name
      favourite_artist_id
      # test aliases with relationships too (ENG-1712):
      my_favourite_artist: favourite_artist {
        name
        artist_id
      }
    }
  }
}
