[package]
name = "hasura-authn-jwt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open-dds = { path = "../open-dds" }
hasura-authn-core = { path = "../hasura-authn-core" }
thiserror = "1.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.92"
serde_with = "2.2.0"
jsonwebtoken = "8.3.0"
reqwest = { version = "0.11.8",  features = ["json"] }
schemars = { version = "0.8.12", features = ["url"] }
url = "2.4.1"
url_serde = "0.2.0"
tracing-util = { path = "../tracing-util"}
jsonptr = { version = "0.4.0" }
lazy_static = "1.4.0"
axum = "0.6.20"
cookie = "0.17.0"
lang-graphql = { path = "../lang-graphql" }

[dev-dependencies]
pretty_assertions = "1.3.0"
tokio = { version = "1.29.0", features = ["macros"] }
jsonwebkey = { version = "0.3.5", features = ["generate", "jsonwebtoken","pkcs-convert"] }
mockito = "1.1.0"
indoc = "2"
openssl = "0.10.60"