# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    org_id: 1
    url: "http://prometheus:9090"
    is_default: true
    version: 1
    editable: true

  - name: Jaeger
    type: jaeger
    # access: proxy
    url: http://jaeger:16686/
    # basicAuth: true
    # basicAuthUser: my_user
    # editable: true
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true
