# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
# resolver: lts-10.8
resolver: lts-13.20
# Local packages, usually specified by relative directory name
packages:
- '.'
# - '../../../graphql-parser-hs'
# - extra-libs/aeson
# - extra-libs/logger/wai-logger

# Make sure `stack build --ghc-options=...` actually (flippin') works:
rebuild-ghc-options: true

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
# use https URLs so that build systems can clone these repos
- git: https://github.com/hasura/pg-client-hs.git
  commit: bd21e66d8197af381a6c0b493e22d611ed1fa386
- git: https://github.com/hasura/graphql-parser-hs.git
  commit: f3d9b645efd9adb143e2ad4c6b73bded1578a4e9
- git: https://github.com/hasura/ci-info-hs.git
  commit: ad6df731584dc89b72a6e131687d37ef01714fe8

# extra dep for pg-client-hs
- select-0.4.0.1

- primitive-extras-0.7.1
- stm-hamt-1.2.0.2
- stm-containers-1.1.0.4
- reroute-0.5.0.0
- Spock-core-0.13.0.0
- monad-validate-1.2.0.0
# needed for Text.Shakespeare.Text.stextFile; can be removed once the newer version is in stackage
- shakespeare-2.0.22

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor

docker:
  enable: false
  repo: 'hasura/stack-build'
