query {
  ArticleMany(
    where: {
      _or: [{ article_id: { _eq: 1 } }, { title: { _like: "something" } }]
    }
  ) {
    title
    article_id
  }

  Author_1: getAuthorById(author_id: 1) {
    id
    last_name
    first_name
  }
}
