[package]
name = "hasura-dev-auth-webhook"
# this does not use the workspace properties so it can be built standalone
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "hasura-dev-auth-webhook"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.80"
axum = "0.6.20"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
