-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Online_users_select_column exposing (Online_users_select_column(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "online\_users"

  - Id - column name
  - Last\_seen - column name

-}
type Online_users_select_column
    = Id
    | Last_seen


list : List Online_users_select_column
list =
    [ Id, Last_seen ]


decoder : Decoder Online_users_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "id" ->
                        Decode.succeed Id

                    "last_seen" ->
                        Decode.succeed Last_seen

                    _ ->
                        Decode.fail ("Invalid Online_users_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Online_users_select_column -> String
toString enum =
    case enum of
        Id ->
            "id"

        Last_seen ->
            "last_seen"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Online_users_select_column
fromString enumString =
    case enumString of
        "id" ->
            Just Id

        "last_seen" ->
            Just Last_seen

        _ ->
            Nothing
