-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Todos_update_column exposing (Todos_update_column(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "todos"

  - Is\_completed - column name
  - Title - column name

-}
type Todos_update_column
    = Is_completed
    | Title


list : List Todos_update_column
list =
    [ Is_completed, Title ]


decoder : Decoder Todos_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "is_completed" ->
                        Decode.succeed Is_completed

                    "title" ->
                        Decode.succeed Title

                    _ ->
                        Decode.fail ("Invalid Todos_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Todos_update_column -> String
toString enum =
    case enum of
        Is_completed ->
            "is_completed"

        Title ->
            "title"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Todos_update_column
fromString enumString =
    case enumString of
        "is_completed" ->
            Just Is_completed

        "title" ->
            Just Title

        _ ->
            Nothing
