-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Users_update_column exposing (Users_update_column(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| update columns of table "users"

  - Last\_seen - column name

-}
type Users_update_column
    = Last_seen


list : List Users_update_column
list =
    [ Last_seen ]


decoder : Decoder Users_update_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "last_seen" ->
                        Decode.succeed Last_seen

                    _ ->
                        Decode.fail ("Invalid Users_update_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Users_update_column -> String
toString enum =
    case enum of
        Last_seen ->
            "last_seen"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Users_update_column
fromString enumString =
    case enumString of
        "last_seen" ->
            Just Last_seen

        _ ->
            Nothing
