version: "3.6"

services:
  dc-reference-agent:
    build:
      context: .
      dockerfile: Dockerfile-reference
    ports:
      - "65005:8100"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - localhost:8100/health
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 20

  dc-sqlite-agent:
    build:
      context: .
      dockerfile: Dockerfile-sqlite
    ports:
      - "65007:8100"
    volumes:
      - "./sqlite/test/db.chinook.sqlite:/db.chinook.sqlite"
      - "./sqlite/test/db.sqlite:/db.sqlite"
    environment:
      METRICS: y
      PRETTY_PRINT_LOGS: y
      LOG_LEVEL: debug
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - localhost:8100/health
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 20
