query MyQuery {
  node(
    id: "eyJ2ZXJzaW9uIjoxLCJ0eXBlbmFtZSI6IkF1dGhvciIsImlkIjp7ImF1dGhvcl9pZCI6MX19"
  ) {
    ... on Author {
      last_name
      author_id
    }
    ... on Article {
      article_id
      title
    }
  }
}
