query MyQuery {
  Album(where: { Tracks: { TrackAlbums: { AlbumId: { _eq: 3 } } } }) {
    AlbumId
    Tracks {
      TrackId
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  AlbumAnd: Album(
    where: {
      _and: [
        { Tracks: { TrackAlbums: { AlbumId: { _eq: 3 } } } }
        { AlbumId: { _eq: 3 } }
      ]
    }
  ) {
    AlbumId
    Tracks {
      TrackId
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  AlbumOr: Album(
    where: {
      _or: [
        { Tracks: { TrackAlbums: { AlbumId: { _eq: 3 } } } }
        { AlbumId: { _eq: 2 } }
      ]
    }
  ) {
    AlbumId
    Tracks {
      TrackId
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  ArtistAlbumAndTrackNotNested: Artist(
    where: {
      _and: [
        { Albums: { Title: { _ilike: "%Rock%" } } }
        { Albums: { Tracks: { Name: { _ilike: "%Rock%" } } } }
      ]
    }
  ) {
    ArtistId
    Name
    Albums {
      AlbumId
      Title
      Tracks {
        TrackId
        Name
      }
    }
  }

  ArtistAlbumAndTrackNested: Artist(
    where: {
      Albums: {
        _and: [
          { Title: { _ilike: "%Rock%" } }
          { Tracks: { Name: { _ilike: "%Rock%" } } }
        ]
      }
    }
  ) {
    ArtistId
    Name
    Albums {
      AlbumId
      Title
      Tracks {
        TrackId
        Name
      }
    }
  }
}
