query ($last_received_id: Int, $last_received_ts: timestamptz){
    message (
      order_by: {timestamp:asc}
      where: {
        _and: {
          id: {
            _neq: $last_received_id
          },
          timestamp: {
            _gte: $last_received_ts
          }
        }
      }
    ) {
      id
      text
      username
      timestamp
    }
  }