// TODO: These types should be replaced by autogenerated types, when we use typescript graphql codegen

type SurveyQuestionOptions = {
  // Note: `option` comes from cloud backend, and is not strongly typed in backend. Hence it is typed as `string`
  // As the form is dynamic in nature, there could be additions/deletions to survey options in future
  option: string;
  id: string;
};

type SurveyQuestion = {
  kind: string;
  question: string;
  id: string;
  survey_question_options: SurveyQuestionOptions[];
};

type SurveyDetail = {
  survey_name: string;
  survey_questions: SurveyQuestion[];
};

export type SurveysResponseData = {
  data: {
    survey: SurveyDetail[];
    survey_question_answers: {
      survey_question_id: string;
    }[];
  };
};

type QuestionAnswersResponse = {
  answer?: string;
  optionsSelected?: string;
  question_id: string;
};

export type QuestionAnswers = {
  surveyName: string;
  responses: QuestionAnswersResponse[];
};
