// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

'use strict';

const EditorJs = require('./Editor.js');

const make = EditorJs.default;

exports.make = make;
/* make Not a pure module */
