query MyQuery {
  Album(limit: 1) {
    Tracks(limit: 2) {
      Album {
        AlbumId
      }
      Genre {
        GenreId
      }
      Name
    }
  }

  Track(limit: 10) {
    TrackId
    Name
    Album {
      AlbumId
      Title
      ArtistId
    }
  }
}
