query MyQuery {
  EvalInstitutions(
    institutions: [
      {
        Id: 1
        Name: "Academy of Science"
        Location: {
          Campuses: [
            "Mile End"
            "Whitechapel"
            "Charterhouse Square"
            "West Smithfield"
          ]
          City: "London"
        }
        Staff: [{ FirstName: "John" }, { FirstName: "Jane" }]
      }
    ]
  ) {
    EvaluationResult
    Institution {
      Id
      Name
      Location {
        Campuses
        City
        Country
      }
      Staff {
        FirstName
        LastName
        Specialities
      }
      Departments
    }
  }
}
