// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require('bs-platform/lib/js/js_dict.js');
var Caml_option = require('bs-platform/lib/js/caml_option.js');

var commonStyles = require('./Common.scss');

function getStyle(className, customStyles) {
  if (customStyles !== undefined) {
    var match = Js_dict.get(Caml_option.valFromOption(customStyles), className);
    if (match !== undefined) {
      return match;
    } else {
      return '';
    }
  } else {
    var match$1 = Js_dict.get(commonStyles, className);
    if (match$1 !== undefined) {
      return match$1;
    } else {
      return '';
    }
  }
}

exports.commonStyles = commonStyles;
exports.getStyle = getStyle;
/* commonStyles Not a pure module */
