query MyQuery {
  Invoice(
    order_by: [{ InvoiceDate: Desc }, { Customer: { CustomerId: Asc } }]
  ) {
    InvoiceId
    InvoiceLines(order_by: { InvoiceId: Asc }) {
      InvoiceLineId
    }
  }
}
