FROM alpine:3.10.3 as wrk2-builder
ARG tag=print-latencies
RUN apk add alpine-sdk openssl-dev zlib-dev luajit-dev
RUN apk add --no-cache git
RUN wget -O /tmp/wrk2.zip https://github.com/hasura/wrk2/archive/$tag.zip
RUN unzip /tmp/wrk2.zip -d /tmp/
RUN make -C /tmp/wrk2-${tag}

FROM alpine:3.10.3
ARG tag=print-latencies
MAINTAINER nizar@hasura.io
RUN apk add wrk lua5.1-cjson
COPY --from=wrk2-builder /tmp/wrk2-$tag/wrk /usr/bin/wrk2
