language: c
# sudo: false
dist: focal

# addons:
#   apt:
#     sources:
#       - sourceline: ppa:redislabs/redis
#     packages:
#       - redis

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install redis-server
  - mkdir -p ~/.local/bin
  - mkdir -p ~/tmp
  - export PATH=~/.local/bin:$PATH
  - curl -L https://github.com/commercialhaskell/stack/releases/download/v2.5.1/stack-2.5.1-linux-x86_64.tar.gz | tar xz -C ~/tmp
  - mv ~/tmp/stack-2.5.1-linux-x86_64/stack ~/.local/bin/
  - cd ${TRAVIS_BUILD_DIR}
  - docker run -d -p 7000-7010:7000-7010 grokzen/redis-cluster:5.0.6

matrix:
  include:
    - env: GHCVER=8.2.2 STACK_YAML=stack-8.2.yaml
    - env: GHCVER=8.4.1 STACK_YAML=stack-8.4.yaml
    - env: GHCVER=8.6.5 STACK_YAML=stack-8.6.yaml
    - env: GHCVER=8.8.1 STACK_YAML=stack-8.8.yaml
    - env: GHCVER=8.10.4 STACK_YAML=stack-8.10.yaml
    - env: GHCVER=8.10.6 STACK_YAML=stack-8.10.yaml

  allow_failures:
   - env: GHCVER=head STACK_YAML=stack-head.yaml

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
