[package]
name = "opendds-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true
bench = false

[dependencies]
convert_case = { workspace = true }
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
syn = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
