query MyQuery {
  Album(limit: 10) {
    Title
    AlbumId
    Tracks {
      Name
      TrackId
      PlaylistTracks {
        TrackId
      }
    }
  }
  CustomerByID(CustomerId: "2") {
    Address
    City
    Company
    Country
    Employee {
      BirthDate
      City
      Fax
      Email
      Employees(limit: 10) {
        BirthDate
        City
      }
    }
  }
}
