query MyQuery {
  Album(where: { Tracks: { TrackAlbums: { AlbumId: { _eq: 3 } } } }) {
    AlbumId
    Tracks {
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  AlbumRemote: Album(
    where: { TracksRemote: { TrackAlbums: { AlbumId: { _eq: 3 } } } }
  ) {
    AlbumId
    TracksRemote {
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  AlbumAnd: Album(
    where: {
      _and: [
        { Tracks: { TrackAlbums: { AlbumId: { _eq: 3 } } } }
        { AlbumId: { _eq: 3 } }
      ]
    }
  ) {
    AlbumId
    Tracks {
      TrackId
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  AlbumAndRemote: Album(
    where: {
      _and: [
        { Tracks: { TrackAlbumsRemote: { AlbumId: { _eq: 3 } } } }
        { AlbumId: { _eq: 3 } }
      ]
    }
  ) {
    AlbumId
    Tracks {
      TrackId
      TrackAlbumsRemote {
        AlbumId
        Title
      }
    }
  }
  AlbumOr: Album(
    where: {
      _or: [
        { Tracks: { TrackAlbums: { AlbumId: { _eq: 3 } } } }
        { AlbumId: { _eq: 2 } }
      ]
    }
  ) {
    AlbumId
    Tracks {
      TrackId
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  AlbumOrRemote: Album(
    where: {
      _or: [
        { TracksRemote: { TrackAlbums: { AlbumId: { _eq: 3 } } } }
        { AlbumId: { _eq: 2 } }
      ]
    }
  ) {
    AlbumId
    TracksRemote {
      TrackId
      TrackAlbums {
        AlbumId
        Title
      }
    }
  }
  ArtistAlbumAndTrackNotNested: Artist(
    where: {
      _and: [
        { Albums: { Title: { _ilike: "%Rock%" } } }
        { Albums: { Tracks: { Name: { _ilike: "%Rock%" } } } }
      ]
    }
  ) {
    Name
  }
  ArtistAlbumAndTrackNotNestedRemote: Artist(
    where: {
      _and: [
        { AlbumsRemote: { Title: { _ilike: "%Rock%" } } }
        { Albums: { TracksRemote: { Name: { _ilike: "%Rock%" } } } }
      ]
    }
  ) {
    Name
  }

  ArtistAlbumAndTrackNested: Artist(
    where: {
      Albums: {
        _and: [
          { Title: { _ilike: "%Rock%" } }
          { Tracks: { Name: { _ilike: "%Rock%" } } }
        ]
      }
    }
  ) {
    Name
  }

  ArtistAlbumAndTrackNestedRemote: Artist(
    where: {
      Albums: {
        _and: [
          { Title: { _ilike: "%Rock%" } }
          { TracksRemote: { Name: { _ilike: "%Rock%" } } }
        ]
      }
    }
  ) {
    Name
  }
}
