query MyQuery {
  getActorsByNameOpaqueSurname(
    name_filter: { first_name: "Leonardo", surname: "DiCaprio" }
  ) {
    movie_id
    name
  }
  getActorsByOpaqueName(
    name_filter: { first_name: "Leonardo", last_name: "DiCaprio" }
  ) {
    movie_id
    name
  }
}
