// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: true,
  serverUrl: "https://api.chucknorris.io",
  defaultLanguage: "en-US",
  supportedLanguages: ["en-US"],
  graphqlEndpoint: "<replace-with-your-endpoint>",
  hasuraAccessKey: "<your-hasura-endpoint-access-key>"
};
