query {
  __schema {
    queryType {
      name
      fields {
        name
        args {
          name
          defaultValue
          type {
            kind
            name
            ofType {
              kind
              name
            }
          }
        }
      }
    }
  }
  type_name_query: __type(name: "NameQuery") {
    name
    kind
    inputFields {
      name
      type {
        kind
        name
        ofType {
          kind
          name
        }
      }
    }
  }
}
