query MyQuery {
  # This should fail - attempting to order by a remote relationship
  # This is raised as a build issue, and is an error with the flag disallow_unsupported_orderable_relationships
  InstitutionMany(
    order_by: [
      { location: { location_country_remote: { name: Desc } } }
      { id: Desc }
    ]
  ) {
    id
    location {
      location_country_remote {
        id
        name
      }
    }
  }
}
