[package]
name = "ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hasura-authn-core = { path = "../auth/hasura-authn-core" }
json-ext = { path = "../utils/json-ext" }
lang-graphql = { path = "../lang-graphql" }
open-dds = { path = "../open-dds" }
schema = { path = "../schema" }
tracing-util = { path = "../utils/tracing-util" }
metadata-resolve = {path = "../metadata-resolve" }

base64 = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
ndc-models = { workspace = true }
nonempty = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
schemars = { workspace = true, features = ["smol_str"] }
serde = { workspace = true }
serde_json = { workspace = true }
smol_str = { workspace = true }
thiserror = { workspace = true }
transitive = { workspace = true }

[lints]
workspace = true
