query MyQuery {
  Track(
    order_by: [
      { Album: { Artist: { ArtistId: Asc } } }
      { AlbumId: Asc }
      { TrackId: Asc }
    ]
    limit: 15
  ) {
    TrackId
    Album {
      AlbumId
      Artist {
        ArtistId
      }
      Title
    }
  }
  TrackOrderByWithFilter: Track(
    order_by: [
      { Album: { Artist: { ArtistId: Desc } } }
      { AlbumId: Asc }
      { TrackId: Asc }
    ]
    where: { AlbumId: { _eq: 2 } }
    limit: 15
  ) {
    TrackId
    Album {
      AlbumId
      Artist {
        ArtistId
      }
      Title
    }
  }
}
