export type ExperimentConfig = {
  experiment: string;
  status: string;
  metadata: ExperimentsResponseData['data']['experiments_config'][0]['metadata'];
  userActivity: ExperimentsResponseData['data']['experiments_cohort'][0]['activity'];
};

// TODO: These types should be replaced by autogenerated types, when we use typescript graphql codegen
type ExperimentsConfig = {
  experiment: string;
  metadata: Record<string, unknown>;
  status: string;
};

type ExperimentsCohort = {
  experiment: string;
  activity: Record<string, unknown>;
};

export type ExperimentsResponseData = {
  data: {
    experiments_config: ExperimentsConfig[];
    experiments_cohort: ExperimentsCohort[];
  };
};
