query MyQuery {
  Analytics {
    analytics {
      analytics {
        analytics {
          ActorFromCommand {
            name
          }
          MovieFromCommand {
            title
            rating
          }
        }
        analytics_id
        movie_id
        total_votes
      }
    }
  }
}
