query MyQuery {
  artist_bool_exp: __type(name: "Artist_Where_Exp") {
    name
    description
    kind
    inputFields {
      name
      description
      type {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
          }
        }
      }
    }
  }
  album_bool_exp: __type(name: "Album_Where_Exp") {
    name
    description
    kind
    inputFields {
      name
      description
      type {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
          }
        }
      }
    }
  }
  track_bool_exp: __type(name: "Track_Where_Exp") {
    name
    description
    kind
    inputFields {
      name
      description
      type {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
          }
        }
      }
    }
  }
}
