query MyQuery {
  Track(order_by: [{ Album: { ArtistId: Desc } }], limit: 3) {
    TrackId
    Album {
      AlbumId
      ArtistId
      Title
    }
  }
  TrackOrderByWithoutRelationshipField: Track(
    order_by: [{ Album: { ArtistId: Desc } }, { Name: Asc }]
    limit: 3
  ) {
    Name
    Album {
      AlbumId
    }
  }
  TrackOrderByWithFilter: Track(
    order_by: [{ Album: { ArtistId: Asc } }, { TrackId: Desc }]
    where: { Album: { Artist: { ArtistId: { _eq: 2 } } } }
  ) {
    TrackId
    Album {
      AlbumId
      Artist {
        ArtistId
        Name
      }
    }
  }
}
