import { useQuery } from '@tanstack/react-query';
import { cloudDataServiceApiClient } from '../../../../../hooks/cloudDataServiceApiClient';
import { isArray, isCloudConsole } from '@hasura/shared/utils';
import { useAppContext } from '@hasura/shared/context';

// TODO: These types should be replaced by autogenerated types, when we use typescript graphql codegen
type NeonProjectsByProjectIdResponseData = {
  data: {
    neon_db_integration: NeonDBIntegrationOptions[];
  };
};

type NeonDBIntegrationOptions = {
  env_var: string | null;
  id: string;
  neon_project_id: string;
};

const FETCH_NEON_PROJECTS_BY_PROJECTID = `
query fetchNeonProjectsByProjectId ($hasura_cloud_project_id: uuid) {
    neon_db_integration(where: {hasura_cloud_project_id: {_eq: $hasura_cloud_project_id}}) {
      env_var
      id
      neon_project_id
    }
  }  
`;

export const FETCH_NEON_PROJECTS_BY_PROJECTID_QUERYKEY = [
  'FETCH_NEON_PROJECTS_BY_PROJECTID_QUERYKEY',
] as const;

const fetchNeonProjectsByProjectIdQueryFn = (projectId: string) => {
  // cloud uses cookie-based auth, so does not require an admin secret
  const headers = {
    'content-type': 'application/json',
  };
  return cloudDataServiceApiClient<NeonProjectsByProjectIdResponseData>(
    FETCH_NEON_PROJECTS_BY_PROJECTID,
    {
      hasura_cloud_project_id: projectId,
    },
    headers,
  );
};

// A stale time of 5 minutes for use in useQuery hook
const staleTime = 5 * 60 * 1000;

export const useShowNeonDashboardLink = () => {
  const { envVars } = useAppContext();
  const isCloudEnv = !!isCloudConsole(envVars);

  const { data } = useQuery({
    queryKey: FETCH_NEON_PROJECTS_BY_PROJECTID_QUERYKEY,
    queryFn: async () => {
      if (!envVars.projectID) {
        return false;
      }

      const result = await fetchNeonProjectsByProjectIdQueryFn(
        envVars.projectID,
      );

      return (
        isCloudEnv &&
        result &&
        isArray(result.data?.neon_db_integration) &&
        result.data?.neon_db_integration.length > 0
      );
    },
    // don't run the query if current environment is not cloud console
    enabled: isCloudEnv,
    staleTime,
  });

  return Boolean(data);
};
