query {
  __type(name: "ActorsByMovieArgs") {
    name
    kind
    inputFields {
      name
      type {
        kind
        name
        ofType {
          kind
          name
        }
      }
    }
  }
}
