import React from 'react';
import Select, { components } from 'react-select';
import PropTypes from 'prop-types';

/*
 * Wrap the option generated by react-select and adds utility properties
 * */
const CustomOption = props => {
  return (
    <div
      title={props.data.description || ''}
      data-test={`data_test_column_type_value_${props.data.value}`}
    >
      <components.Option {...props} />
    </div>
  );
};

/*
 * Searchable select box component
 *  1) options: Accepts options
 *  2) value: selectedValue
 *  3) onChange: function to call on change of value
 *  4) bsClass: Wrapper class
 *  5) customStyle: Custom style
 * */
const SearchableSelectBox = ({
  options,
  onChange,
  value,
  bsClass,
  styleOverrides,
}) => {
  /* Select element style customization */

  const customStyles = {};
  if (styleOverrides) {
    Object.keys(styleOverrides).forEach(comp => {
      customStyles[comp] = provided => {
        return {
          ...provided,
          ...styleOverrides[comp],
        };
      };
    });
  }

  return (
    <Select
      isSearchable
      components={{ Option: CustomOption }}
      classNamePrefix={`${bsClass}`}
      placeholder="column_type"
      options={options}
      onChange={onChange}
      value={value}
      styles={customStyles}
    />
  );
};

SearchableSelectBox.propTypes = {
  value: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired,
  options: PropTypes.array.isRequired,
  bsClass: PropTypes.string,
  customStyle: PropTypes.object,
};

export default SearchableSelectBox;
