query {
  Customer(
    where: { CustomerId: { _in: [48, 17, 21] } }
    order_by: { CustomerId: Asc }
  ) {
    CustomerId
    Invoices_aggregate(
      filter_input: {
        where: { Total: { _gt: 2 } }
        order_by: { InvoiceId: Asc }
        offset: 1
        limit: 2
      }
    ) {
      InvoiceDate {
        _min
        _max
        _count_distinct
      }
      InvoiceId {
        min: _min
        max: _max
        count: _count
      }
      Total {
        _min
        _max
        _sum
        _stddev
      }
      count_all: _count
    }
  }
}
