- args:
    sql: CREATE TABLE "public"."article"("id" serial NOT NULL, "title" text NOT NULL,
      "author_id" integer NOT NULL, PRIMARY KEY ("id") );
  type: run_sql
- args:
    name: article
    schema: public
  type: add_existing_table_or_view
