- args:
    permission:
      allow_aggregations: true
      columns:
      - id
      - name
      filter:
        id:
          _eq: X-Hasura-User-Id
      limit: null
    role: user
    table:
      name: author
      schema: public
  type: create_select_permission
