- args:
    permission:
      allow_aggregations: true
      columns:
      - author_id
      - id
      - title
      filter:
        author_id:
          _eq: X-Hasura-User-Id
      limit: null
    role: user
    table:
      name: article
      schema: public
  type: create_select_permission
