- args:
    permission:
      allow_upsert: true
      check:
        id:
          _eq: X-Hasura-User-Id
      columns:
      - name
      set:
        id: x-hasura-user-id
    role: user
    table:
      name: author
      schema: public
  type: create_insert_permission
