- args:
    permission:
      columns:
      - name
      filter:
        id:
          _eq: X-Hasura-User-Id
      set: {}
    role: user
    table:
      name: author
      schema: public
  type: create_update_permission
