query {
  Invoice_aggregate(
    filter_input: { where: null, order_by: null, offset: null, limit: null }
  ) {
    BillingState {
      _min
      _max
      _count_distinct
    }
    InvoiceId {
      min: _min
      max: _max
      count: _count
    }
    Total {
      _min
      _max
      _sum
      _stddev
    }
    count_all: _count
  }
}
