on: pull_request
name: compress_images
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.9.0
      with:
        script: |
          const labels = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
          });
          for (const label of labels.data) {
            if (label.name === 'docs-compress-images') {
              return;
            }
          }
          const files = await github.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
          let imagesPresent = false; 
          for (const file of files.data) {
            console.log(file.filename)
            if (file.filename.match(/docs\/.+.png/i)) {
              imagesPresent = true;
              break;
            }
          }
          if (imagesPresent) {
            core.setFailed('compress images and add the docs-compress-images label');
          }
