name: image
on: 
  pull_request:
    paths:
      - 'docs/**/*.jpg'
      - 'docs/**/*.jpeg'
      - 'docs/**/*.png'
      - 'docs/**/*.webp'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.9.0
      with:
        script: |
          const labels = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
          });
          let label_present=false;
          for (const label of labels.data) {
            if (label.name === 'docs-compress-images') {
              label_present=true;
            }
          }
          if(!label_present){
            core.setFailed('docs-compress-images label is required');
          }