name: console lint
on:
  pull_request:
    paths:
      - 'console/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./console

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Use Node.js 12
        uses: actions/setup-node@b6651e20e530d6e6b845a9828606779e89f5529c # v1
        with:
          node-version: 12.x

      - name: Install
        working-directory: ${{env.working-directory}}
        run: npm ci

      - name: Lint
        working-directory: ${{env.working-directory}}
        run: npm run lint:quiet

      - name: Format
        working-directory: ${{env.working-directory}}
        run: npm run format:check
