query {
  Invoice_aggregate {
    BillingCountry {
      _min
      _max
      _count_distinct
    }
    InvoiceId {
      min: _min
      max: _max
      count: _count
    }
    Total {
      _min
      _max
      _sum
      _stddev
    }
    count_all: _count
  }
}
