[package]
name = "lang-graphql"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
lexical-core = "0.8"
indexmap = { version = "2", features = ["serde"] }
nonempty = { version = "0.8", features = ["serialize"] }
logos = "0.12"
smol_str = "0.1.23"
serde = "1.0.152"
serde_json = "1.0.92"
serde_with = "2.2.0"
schemars = { version = "0.8.12", features = ["smol_str"] }
axum-core = "0.3.4"
axum = "0.6.20"
http = "0.2.9"

[dev-dependencies]
apollo-parser = "0.4"
criterion = { version = "0.4", features = ["html_reports"] }
graphql-parser = "0.4"
async-graphql-parser = "5.0"
pretty_assertions = "1.3.0"
rmp-serde = "1.1.1"
postcard = { version = "1.0.4", features = ["use-std"] }
bson = "2.6.0"
bincode = "1.3.3"
human_bytes = "0.4.1"
diffy = "0.3.0"
expect-test = "1.4"

[[bench]]
name = "lexer"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "validation"
harness = false

[[bench]]
name = "schema_serde"
harness = false
